### ISSUE TITLE
Expansion Not Registering Successfully

### ISSUE THREAD

**Issue by NicBOMB** [thienbao860/SpeedPerSec-Expansion#2]
https://github.com/PlaceholderAPI/PlaceholderAPI/issues/515#issuecomment-751391491
The above issue has the context for the error caused by SpeedPerSec in registering PAPI expansions.

**Comment by ghost** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/issues/515#issuecomment-751487561
Also tested on PAPI dev build.

**Comment by Andre601** [comment]
Hey there,

I'm from the above-mentioned discussions.
The issue seems to be that the jar on the ecloud doesn't contain any classes whatsoever which could either be caused by a malformed build on your end or perhaps a malformed upload to the ecloud.

I downloaded the jar quickly and used a decompiler to check this which confirmed my assumption. So it should be updated to fix this.

**Comment by WickyPlays** [comment]
Hello, author of SpeedPerSec expansion here. Since I have very little time to update my current expansion because currently I am focused on Javascript-Expansion. But I will try to maintain this for you. Thanks for report

**Comment by WickyPlays** [comment]
Fixed now. You can now download version 1.2.0 for fixes
